apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - nginx-configmap.yaml
  - nginx-deployment.yaml
  - nginx-service.yaml
  - nginx-ingressroute.yaml

nameSuffix: "-pathbased"
namespace: nginx