apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: nginx-ingressroute
spec:
  entryPoints:
  - websecure # web is by default redirected to websecure
  routes:
  - match: PathPrefix(`/`)
    kind: Rule
    middlewares:
    - name: strip-nginx
    services:
    - name: nginx
      port: 80
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: strip-nginx
spec:
  stripPrefix:
    prefixes:
    - /nginx

