apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: nginx-http-redirect
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`nginx.example.com.np`) && PathPrefix(`/`) # Replace with your domain
      kind: Rule
      middlewares:
        - name: redirect-to-https
      services:
        - name: nginx-service
          port: 80
